sparkApp:
  name: test-spark-app
  namespace: default
  image: rajendar38/spark-helloworld-java:latest
  imagePullPolicy: IfNotPresent
  mainClass: com.example.HelloWorld
  mainApplicationFile: local:///opt/spark/examples/jars/helloworld-java.jar
  type: Java
  mode: cluster
  sparkVersion: "3.4.0"

  schedule: "@every 1m"        # only for ScheduledSparkApplication
  concurrencyPolicy: Forbid    # only for ScheduledSparkApplication

  restartPolicy:
    type: Never

  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark

  executor:
    instances: "2"
    cores: 1
    memory: 512m
